services:
    nekstati.antibot42.fuBSo:
        class: nekstati\antibot42\fuBSo
        arguments:
            - '@nekstati.antibot42.cIaPn'
            - '@nekstati.antibot42.fu4tB'
        tags:
            - { name: event.listener }

    nekstati.antibot42.fu4tB:
        class: nekstati\antibot42\fu4tB
        arguments:
            - '@auth'
            - '@config'
            - '@request'
            - '@template'
            - '@user'
            - '%core.root_path%'
            - '%core.php_ext%'
            - '@nekstati.antibot42.d0rOz'
        tags:
            - { name: event.listener }

    nekstati.antibot42.cIaPn:
        class: nekstati\antibot42\cIaPn
        arguments:
            - '@config'
            - '@request'
            - '@template'
            - '@user'
            - '%core.root_path%'
            - '%core.php_ext%'

    nekstati.antibot42.d0rOz:
        class: nekstati\antibot42\d0rOz
        arguments:
            - '@config'
            - '@controller.helper'
            - '@dbal.conn'
            - '@template'
            - '@user'
            - '%core.root_path%'
        calls:
            - [uFcLp, ['@?router']] # Optional service that doesn’t exist in phpBB 3.1
