services:
    nekstati.antibot42.VkwMF:
        class: nekstati\antibot42\VkwMF
        arguments:
            - '@nekstati.antibot42.RZnJl'
            - '@nekstati.antibot42.HIFRp'
        tags:
            - { name: event.listener }

    nekstati.antibot42.HIFRp:
        class: nekstati\antibot42\HIFRp
        arguments:
            - '@config'
            - '@request'
            - '@template'
            - '@user'
            - '%core.root_path%'
            - '%core.php_ext%'
            - '@nekstati.antibot42.pymWq'
        tags:
            - { name: event.listener }

    nekstati.antibot42.RZnJl:
        class: nekstati\antibot42\RZnJl
        arguments:
            - '@config'
            - '@request'
            - '@template'
            - '@user'
            - '%core.root_path%'
            - '%core.php_ext%'

    nekstati.antibot42.pymWq:
        class: nekstati\antibot42\pymWq
        arguments:
            - '@config'
            - '@controller.helper'
            - '@dbal.conn'
            - '@template'
            - '@user'
            - '%core.root_path%'
        calls:
            - [SgSeA, ['@?router']]
