services:
    nekstati.antibot42.jzDAu:
        class: nekstati\antibot42\jzDAu
        arguments:
            - '@nekstati.antibot42.bkfp0'
            - '@nekstati.antibot42.on5nc'
        tags:
            - { name: event.listener }

    nekstati.antibot42.on5nc:
        class: nekstati\antibot42\on5nc
        arguments:
            - '@config'
            - '@request'
            - '@template'
            - '@user'
            - '%core.root_path%'
            - '%core.php_ext%'
            - '@nekstati.antibot42.ZH33U'
        tags:
            - { name: event.listener }

    nekstati.antibot42.bkfp0:
        class: nekstati\antibot42\bkfp0
        arguments:
            - '@config'
            - '@request'
            - '@template'
            - '@user'
            - '%core.root_path%'
            - '%core.php_ext%'

    nekstati.antibot42.ZH33U:
        class: nekstati\antibot42\ZH33U
        arguments:
            - '@dbal.conn'
            - '@user'
            - '@config'
            - '@controller.helper'
            - '@template'
            - '%core.root_path%'
        calls:
            - [G2WyO, ['@?router']]
