services:
    nekstati.antibot42.PA9a7:
        class: nekstati\antibot42\PA9a7
        arguments:
            - '@nekstati.antibot42.ravC9'
            - '@nekstati.antibot42.T39oe'
        tags:
            - { name: event.listener }

    nekstati.antibot42.T39oe:
        class: nekstati\antibot42\T39oe
        arguments:
            - '@auth'
            - '@config'
            - '@request'
            - '@template'
            - '@user'
            - '%core.root_path%'
            - '%core.php_ext%'
            - '@nekstati.antibot42.X3Gh8'
        tags:
            - { name: event.listener }

    nekstati.antibot42.ravC9:
        class: nekstati\antibot42\ravC9
        arguments:
            - '@config'
            - '@request'
            - '@template'
            - '@user'
            - '%core.root_path%'
            - '%core.php_ext%'

    nekstati.antibot42.X3Gh8:
        class: nekstati\antibot42\X3Gh8
        arguments:
            - '@config'
            - '@controller.helper'
            - '@dbal.conn'
            - '@template'
            - '@user'
            - '%core.root_path%'
        calls:
            - [s_4wP, ['@?router']]
